language: python
python:
  - "2.7"

before_script:
- ls
- pwd
- export PYTHONPATH=/home/travis/build/SingaporeClouds/education/google_appengine/
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/django-1.2/
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/webapp2-2.5.2/
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/webob_0_9/
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/

# command to install dependencies
install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip && unzip -q google_appengine_1.8.9.zip
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

# command to run tests
#script:  python unittests/test_main.py
script: "./runtests.py --gae-lib-root=./google_appengine --with-cover --cover-package=education"
