application: nextucloud
version: development
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on

libraries:
- name: pycrypto
  version: "2.6"

handlers:
- url: /static
  static_dir: static
  expiration: 1m

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^pydev/.*$